import {
  Button,
  NavBar,
  Field,
  CellGroup,
  Form,
  Popup,
  Dialog,
  Toast,
  Tabs,
  Tab,
  Row,
  Divider,
  DatePicker,
  Col,
  Icon,
  Image,
  Lazyload,
  Search,
  Switch,
  Card,
  Radio,
  RadioGroup,
  Picker,
  DropdownMenu,
  DropdownItem,
  Swipe,
  SwipeItem,
  NoticeBar,
  Tag,
  Area,
  Uploader,
  Cell,
  Progress,
  Circle,
  List,
  PullRefresh,
  Steps,
  Step,
  Cascader,
  Empty,
  Tabbar,
  TabbarItem,
  PickerGroup
} from 'vant'

const Components: Array<any> = []
Components.push(Divider)
Components.push(Cascader)
Components.push(DatePicker)
Components.push(Button)
Components.push(Switch)
Components.push(NavBar)
Components.push(Field)
Components.push(CellGroup)
Components.push(Form)
Components.push(Popup)
Components.push(Dialog)
Components.push(Toast)
Components.push(Row)
Components.push(Col)
Components.push(Icon)
Components.push(Image)
Components.push(Lazyload)
Components.push(Search)
Components.push(Tabs)
Components.push(Tab)
Components.push(Card)
Components.push(Radio)
Components.push(RadioGroup)
Components.push(Picker)
Components.push(DropdownMenu)
Components.push(DropdownItem)
Components.push(Swipe)
Components.push(SwipeItem)
Components.push(NoticeBar)
Components.push(Tag)
Components.push(Area)
Components.push(Uploader)
Components.push(Cell)
Components.push(Progress)
Components.push(Circle)
Components.push(List)
Components.push(PullRefresh)
Components.push(Steps)
Components.push(Step)
Components.push(Empty)
Components.push(Tabbar)
Components.push(TabbarItem)
Components.push(PickerGroup)

export default Components
